acc: 1
auto_lr: True
auto_batch: False
batch_size: 8
checkpoint: True
early_stopping: True
effective_batch_size: -1
fast_dev_run: False
gpus: -1
limit_batches: 1.0
lr: 0.0001
max_time: ""
monitor: False
num_workers: 12
